### ISSUE TITLE
Log in/sign up

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#1]
EPIC: Account and Account 
Management

As a user, I want to log in and 
sign up for an account so that 
I can access the platform's 
features.

**Acceptance Criteria**

- Users can sign up with an 
email and password.

- Users must confirm their password 
during sign-up.

- Users can log in with their 
credentials.

- There must be a requirement to 
accept the terms and privacy policy 
during signup.

- Records should be registered and 
kept about the users' birth date.

**Tasks**

- [ ] Design and implement a 
user-friendly sign-up and login 
page.

- [ ] Add password confirmation 
functionality.

- [ ] Validate input fields (e.g., email 
format, password strength).

- [ ] Display error messages for 
incorrect credentials.

- [ ] Add required checkboxes 
for terms and privacy policy
at the signup page.

- [ ] Add a required birth date field.
