### ISSUE TITLE
Rate posts

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#10]
**Epic**  
User Engagement

**Story points**  
2

**User story**

    As a user, I want to rate other users' posts based on how 
    useful, time-saving, or cost-effective I find them, so that I 
    can provide meaningful feedback and help improve 
    content quality on the platform.

**Acceptance Criteria**

• Logged in users can view and rate posts on three criteria:
• Saves Money
• Saves Time
• Usefulness

- Ratings can be adjusted using interactive sliders.

- Users cannot rate their own posts.

- Average scores for each criterion are calculated and displayed on the post.

- Ensure non-authenticated users cannot use this feature.

**Tasks**

- [x] Build an engagement panel with interactive sliders for the ratings.

- [x] Block non-users from submitting ratings. 

- [x] Block non-authenticated users from altering this part of the database.

- [x] Connect the user's rating to their user ID.

- [x] Ensure non-authenticated users cannot use this feature.

- [x] Add validation (eg,. min, max values)
