### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#12]
**Epic**  
User Engagement

**Story points**  
3

**User story**

    As a user, I want to comment on posts so that I can give 
    feedback and show my appreciation.

**Acceptance Criteria**

- Logged-in users can comment on recipes through a simple and user friendly UI. 

- Logged-in users can view other users' comments on posts.

**Tasks**

- [x] Add a comment button.

- [x] Design a comment section that lists users comments

- [x] Add an input field for users who wants to comment.

- [x] All comments should include the following:
• Username
• Creation date

- [x] Add validation for comment input (e.g., character limit).

- [x] Ensure non-authenticated users cannot use this feature.
