### ISSUE TITLE
Age restrictions

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#14]
**Epic**  
User Experience and Design

**Story points**  
2

**User story**

    As a user, I want my children to explore the app more safely 
    without encountering adult content so that they don't hurt 
    themselves mentally or physically.

**Acceptance Criteria**

- When a user creates a post, they are asked about dangerous materials and tools included.

- Users can toggle a checkbox that indicate that the result or outcome of the build/idea may not be safe for children.

- Based on account information, users under the age of 18 will not see posts labeled as dangerous or inappropriate for children.

**Tasks**

- [x] Design a section where users can inform the app about the safety of their submission. 

- [x] Hide posts that may be harmful for kids with backend logic.

- [x] Integrate a system that only shows age-restricted posts to users who are logged in and are above a certain age.
