### ISSUE TITLE
Save posts

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#17]
**Epic**  
User Experience and Design

**Story points**  
2

**User story**

    As a user, I want to save posts so that I can easily 
    access them later.

**Acceptance Criteria**

- Authenticated users can save links to posts on their account by clicking a button. 

**Tasks**

- [ ] Design a save post button

- [ ] Design a section that lists all saved posts.

- [ ] Implement a saving system that stores post links for individual users.
