### ISSUE TITLE
login/signup

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#2]
**Epic**  
Account and Account Management

**Story points**  
3

**User story**

    As a user, I want to log in and sign up for an account so that 
    I can access the platform's features.

**Acceptance Criteria**

- Users can sign up with an email and password.

- Users must confirm their password during sign-up.

- Users can log in with their credentials.

- There must be a requirement to accept the terms and privacy policy during signup.

- Records should be registered and kept about the users' birth date.

**Tasks**

- [x] Design and implement a user-friendly sign-up and login page.

- [x] Add password confirmation functionality.

- [x] Validate input fields (e.g., email format, password strength).

- [x] Display error messages for incorrect credentials.

- [x] Add required checkboxes for terms and privacy policy at the signup page.

- [x] Add a required birth date field.
