### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#3]
**Epic**  
Account and Account Management

**Story points**  
3

**User story**

    As a user, I want to delete my account so that I can leave the 
    platform if needed.

**Acceptance Criteria**

- Users can delete their accounts by clicking a button.

- There should be a security wall to prevent accidental account deletions.

**Tasks**

- [x] Create a profile page with an 
account management section.

- [x] Design a password confirmation component.

- [x] Securely remove user data from the database.
