### ISSUE TITLE
Delete posts

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#7]
**Epic**  
Post Creation, Deletion, and Management

**Story points**  
1

**User story**

    As a user, I want to delete my previously published posts 
    so that I can remove outdated or unwanted content.

**Acceptance Criteria**

- The user can delete a previously published post from the database.

- There should be a security wall to prevent accidental deletions.

**Tasks**

- [x] Add a delete button for posts.

- [x] Implement a system to handle post removals.

- [x] Add an extra layer of security to prevent the user from deleting the recipe by mistake.
