### ISSUE TITLE
Post search

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/reoptinew#8]
**Epic**  
Filtering, Querying, and Ordering.

**Story points**  
3

**User story**

    As a user, I want to search for other users' posts 
    so that I can quickly find builds/ideas that I am interested in.

**Acceptance Criteria**

- Users can search posts based on the following: 
• Title
• Tags
• Description
• Materials
• Tools

**Tasks**

- [x] Design an easily accessible search bar.

- [x] Connect a search object with all search-related data in it to the search bar and corresponding components.

- [x] Validate and use the frontend data in the backend
